# Generated by Django 3.1 on 2023-07-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_auto_20230731_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emp_id',
            new_name='idNo',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
